apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: blrpt-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blrpt
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: blrpt
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: blrpt-container
        image: #Docker registery#
        imagePullPolicy: IfNotPresent
        env:
        - name: ELASTICSEARCH_NODEURLS
          valueFrom:
            configMapKeyRef:
              name: boilerplateapi-config
              key: ELASTICSEARCH_NODEURLS
        - name: ELASTICSEARCH_REQUESTTIMEOUT_MS
          valueFrom:
            configMapKeyRef:
              name: boilerplateapi-config
              key: ELASTICSEARCH_REQUESTTIMEOUT_MS
        ports:
        - name: blrpt-port
          containerPort: 80
        readinessProbe:
          successThreshold: 1
          failureThreshold: 3
          httpGet:
            path: /healthcheck
            port: blrpt-port
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 30
        livenessProbe:
          successThreshold: 1
          failureThreshold: 3
          httpGet:
            path: /healthcheck
            port: blrpt-port
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 30
      imagePullSecrets:
        - name: #Docker registery secrets#
      restartPolicy: Always