version: '3.4'

services:
  gateway:
    image: gateway
    build:
      context: ./src/Pantokrator.Gateway
      dockerfile: Dockerfile
    environment:
    - OrderingUrl=http://orderapi
    - ASPNETCORE_ENVIRONMENT=Production
    - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
    - "5100:80"
    depends_on:
    - orderapi
    - consul

  orderapi:
    image: orderapi   
    build:
      context: ./src/Pantokrator.Order.Api
      dockerfile: Dockerfile
    expose:
    - "80"
    ports:
    - "5200:80"
    depends_on:
    - redis.data
    environment:
    - HOSTNAME=orderapi
    - ASPNETCORE_ENVIRONMENT=Production
    - ASPNETCORE_URLS=http://0.0.0.0:80

  redis.data:
    image: redis

  consul:
    image: consul